# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c73c294739f17c0e4431b29f76cad0d5893ab3f3b40110d5432b855393641e4a2aa0f1dcd3690dba901b80ec1645ca7a2d589a7d7b96888590ca08e640776e4e

test:
  secret_key_base: b49b219e36e3f1161d65b971eed668b43b6f0bf7ef7b6e0cc30eeaad88e10519217ab900a4715227910341803bf2dde97b29e3c6fee85133d7367a12aac8a750

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
